# Generated by Django 3.2.8 on 2023-12-11 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(max_length=500)),
                ('categoryLink', models.CharField(blank=True, default='', max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=500)),
                ('productLink', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('packing', models.CharField(max_length=50)),
                ('crop', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('images', models.ImageField(upload_to='images/')),
                ('isLive', models.BooleanField(default=False)),
                ('isLatest', models.BooleanField(default=False)),
                ('isHot', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.category')),
            ],
        ),
    ]
