# Generated by Django 3.2.8 on 2023-12-19 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_product_listdes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='listdes',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
