# Generated by Django 3.2.8 on 2023-12-24 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_product_isdeleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('lastName', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('contectno', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=100)),
                ('selected_category', models.CharField(max_length=50)),
                ('selected_product', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('time', models.TimeField(auto_now=True)),
            ],
        ),
    ]
